{
 "title": "Platform Overview",
 "tags": [ "cd-indicators" ],
 "time": { "from": "now-14d", "to": "now" },
 "panels": [
  { "title": "Deployment Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Undeployed Releases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH deployed_releases AS (\n\tselect \n\t\td.repository,\n\t\tmax(string_to_array(d.version, '.')::int[]) as version,\n\t\tmax(r.release_time) as release_time,\n\t\tmax(d.deployment_time) as deployment_time\n\tfrom\n\t\tdeployments d\n\tleft join\n\t\treleases r\n\ton r.version = d.version\n\twhere d.environment ilike 'prod%'\n\tgroup by d.repository\n\torder by repository asc\n\t)\nSELECT\n\tcount(r.version) as version\nFROM\n\treleases r,\n\tdeployed_releases d\nWHERE\n\tr.repository = d.repository AND\n\tr.release_time > d.release_time;"
    }
   ]
  },
  {
   "title": "Applications with Undeployed Releases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "WITH deployed_releases AS (\n\tselect \n\t\td.repository,\n\t\tmax(string_to_array(d.version, '.')::int[]) as version,\n\t\tmax(r.release_time) as release_time,\n\t\tmax(d.deployment_time) as deployment_time\n\tfrom\n\t\tdeployments d\n\tleft join\n\t\treleases r\n\ton r.version = d.version\n\twhere d.environment ilike 'prod%'\n\tgroup by d.repository\n\torder by repository asc\n\t)\nSELECT\n  r.release_time as \"time\",\n\tr.repository as metric,\n\tcount(r.version) as version\nFROM\n\treleases r,\n\tdeployed_releases d\nWHERE\n\tr.repository = d.repository AND\n\tr.release_time > d.release_time\nGROUP BY 1,2\nORDER BY metric ASC;"
    }
   ]
  },
  { "title": "Period Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Contributors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count (distinct author)\nFROM\n  pull_requests\nWHERE\n  $__timeFilter(creation_time)\n"
    }
   ]
  },
  {
   "title": "Reviews",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum (reviews)\nFROM\n  pull_requests\nWHERE\n  $__timeFilter(creation_time)\n"
    }
   ]
  },
  {
   "title": "Pull Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  pull_requests\nWHERE\n  ($__timeFilter(creation_time) OR $__timeFilter(ready_for_review_time) OR $__timeFilter(approved_time) OR $__timeFilter(merged_time))\n"
    }
   ]
  },
  {
   "title": "Time To Review",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  approved_time as \"time\",\n  time_to_review\nFROM\n  pull_requests\nWHERE\n  $__timeFilter(approved_time)\n"
    }
   ]
  },
  {
   "title": "Pull Requests",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  case when state='open' then creation_time when state='closed' and merged_time is not null then merged_time else creation_time end as \"time\",\n  case when state='open' then 'open' when state='closed' and merged_time is not null then 'merged' else 'closed' end as \"metric\",\n  1 as \"value\"\nFROM pull_requests\nWHERE\n  ($__timeFilter(creation_time) OR $__timeFilter(merged_time))\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Release Interval",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH one AS (\n\tSELECT\n\t\trepository,\n\t\trelease_time,\n\t\tlag(release_time) OVER (ORDER BY repository, release_time) AS previous_release_time,\n\t\trelease_time - lag(release_time) OVER (ORDER BY repository, release_time) AS diff\n\tFROM releases\n\t),\n\ttwo AS (\n\tSELECT\n\t\trepository,\n\t\trelease_time,\n\t\tcase when extract (epoch from diff) > 0 then extract (epoch from diff) else 0 end as diff_seconds\n\tFROM one\n\t)\nSELECT\n  percentile_cont(0.5) WITHIN GROUP (ORDER BY diff_seconds) as median,\n  stddev_pop(diff_seconds) as stddev\nFROM two\nWHERE\n  $__timeFilter(release_time)"
    }
   ]
  },
  {
   "title": "Releases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  releases\nWHERE\n  $__timeFilter(release_time)\n"
    }
   ]
  },
  {
   "title": "Deployed Releases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "WITH r AS (\n\tselect \n\t\tcount(version) as releases\n\tfrom\n\t\treleases\n\twhere $__timeFilter(release_time)\n\t),\n\td AS (\n\tselect\n\t\tcount(distinct(version)) as deployed_releases\n\tfrom\n\t\tdeployments\n\twhere environment ilike 'prod%' AND $__timeFilter(deployment_time)\n\t)\nSELECT\n\td.deployed_releases::float/r.releases::float as ratio\nFROM\n\tr, d;"
    }
   ]
  },
  {
   "title": "Releases",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  release_time AS \"time\",\n  1\nFROM releases\nWHERE\n  $__timeFilter(release_time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Deployment Interval",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH one AS (\n\tSELECT\n\t\trepository,\n\t\tenvironment,\n\t\tdeployment_time,\n\t\tlag(deployment_time) OVER (ORDER BY repository, environment, deployment_time) AS previous_deployment_time,\n\t\tdeployment_time - lag(deployment_time) OVER (ORDER BY repository, environment, deployment_time) AS diff\n\tFROM deployments\n\t),\n\ttwo AS (\n\tSELECT\n\t\trepository,\n\t\tenvironment,\n\t\tdeployment_time,\n\t\tcase when extract (epoch from diff) > 0 then extract (epoch from diff) else 0 end as diff_seconds\n\tFROM one\n\t)\nSELECT\n  percentile_cont(0.5) WITHIN GROUP (ORDER BY diff_seconds) as median,\n  stddev_pop(diff_seconds) as stddev\nFROM two\nWHERE\n  $__timeFilter(deployment_time) AND environment ilike 'prod%'"
    }
   ]
  },
  {
   "title": "Stag. Deployments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  deployments\nWHERE\n  $__timeFilter(deployment_time) AND environment ilike 'stag%'\n"
    }
   ]
  },
  {
   "title": "Prod Deployments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM\n  deployments\nWHERE\n  $__timeFilter(deployment_time) AND environment ilike 'prod%'\n"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  deployment_time AS \"time\",\n  environment AS metric,\n  1\nFROM deployments\nWHERE\n  $__timeFilter(deployment_time)\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Pipelines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Pipelines Duration",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  context AS metric,\n  duration\nFROM pipelines\nWHERE\n  $__timeFilter(start_time)\nORDER BY \"time\", metric ASC"
    }
   ]
  },
  {
   "title": "Pipelines Duration",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  context AS metric,\n  duration\nFROM pipelines\nWHERE\n  $__timeFilter(start_time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Pipelines Failure Rate",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n\t(p.failed::decimal/p.total::decimal)*100 as rate,\n\tp.context\nFROM\n  (\n  SELECT \n    count(1) AS total, \n    count(1) FILTER (WHERE status='Succeeded') AS success, \n    count(1) FILTER (WHERE status!='Succeeded') AS failed, \n    context \n  FROM pipelines \n  WHERE $__timeFilter(start_time) GROUP BY context\n  ) as p\nORDER BY rate DESC"
    }
   ]
  }
 ]
}